version: "2"

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "LexisTrainer.app:create_app()"
    environment:
      PYTHONUNBUFFERED: "true"
    volumes:
      - ".:/LexisTrainer"
    ports:
      - "8000:8000"
